# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_info_data",  {
 output <- get_info_data(iris)
# Tet that the function returns something of length 2
  expect_equal(length(output), 2)
#  expect_type(list(output[["dimensions"]],output[["column_names"]]))
# that the first element is a numeric of size 2
# that the first element is a numeric of size 2
# use dput to test if the output is the expected output

})
