# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' get_info_data()
#' this function take the data frame any data frame #'dimension and names 
#'
#' @return List of 2 elements Dimension and Name,
#' @param  data_df it is a data frame
#' @export
#'
#' @examples
#' df_1 <- data.frame(c = 3 , d =4)
#' get_info_data(df_1)
get_info_data <- function(data_df) {
   stopifnot( is.data.frame(data_df))
my_list <- list( dimensions = dim(data_df), column_names = names(data_df))
  return(my_list)
}
